


set(OUTPUT_DIR ${PROJECT_SOURCE_DIR}/../${PREFIX_DIR})

message(STATUS "[${PROJECT_NAME}]" OUTPUT_DIR:${OUTPUT_DIR})

set_target_properties(${PROJECT_NAME} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG              "${OUTPUT_DIR}"
    LIBRARY_OUTPUT_DIRECTORY_DEBUG              "${OUTPUT_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_DEBUG              "${OUTPUT_DIR}"
    PDB_OUTPUT_DIRECTORY_DEBUG                "${OUTPUT_DIR}"

    ARCHIVE_OUTPUT_DIRECTORY_RELEASE             "${OUTPUT_DIR}"
    LIBRARY_OUTPUT_DIRECTORY_RELEASE             "${OUTPUT_DIR}"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE             "${OUTPUT_DIR}"
    PDB_OUTPUT_DIRECTORY_RELEASE               "${OUTPUT_DIR}"
)